// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyCurwHg3ckTSZOz617yvEl2anZq0gcZ72c',
//     appId: '1:868253715625:web:8d3e621c5c1778a7a5adb8',
//     messagingSenderId: '868253715625',
//     projectId: 'meetup-dating-app',
//     authDomain: 'meetup-dating-app.firebaseapp.com',
//     storageBucket: 'meetup-dating-app.appspot.com',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBOSJ63cESH8AuuXvGbhQ9EabxsKquEHMs',
//     appId: '1:868253715625:android:a75ed4c4b099a90ea5adb8',
//     messagingSenderId: '868253715625',
//     projectId: 'meetup-dating-app',
//     storageBucket: 'meetup-dating-app.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyD1uDPPZCApmrznbf4x6Yf9oIoWHLIi5Pg',
//     appId: '1:868253715625:ios:00b054680d929074a5adb8',
//     messagingSenderId: '868253715625',
//     projectId: 'meetup-dating-app',
//     storageBucket: 'meetup-dating-app.appspot.com',
//     iosBundleId: 'com.example.datingApp',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyD1uDPPZCApmrznbf4x6Yf9oIoWHLIi5Pg',
//     appId: '1:868253715625:ios:ad90318e459c77e9a5adb8',
//     messagingSenderId: '868253715625',
//     projectId: 'meetup-dating-app',
//     storageBucket: 'meetup-dating-app.appspot.com',
//     iosBundleId: 'com.example.datingApp.RunnerTests',
//   );
// }
